### ISSUE TITLE
awestruct 0.5.3 does not work

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian.github.com#267]
bundle installs 0.5.3 but it gives some error in connection to "listen" module, pretty much this one:

https://github.com/ceylon/ceylon-lang.org/issues/252

So I override awestruct in Gemfile to use (just released) 0.5.4.rc2 and listen 1.3.1 but it has some issues with tilt.

    Using profile: development
    Generating site: http://localhost:4242
    While processing file 
    An error occurred: undefined method `mappings' for Tilt:Module

Not sure what is the next step so writing ... 

I am using tilt 2.0.0 as bundle show tilt gives me.

**Comment by bartoszmajsak** [comment]
Fixed with the new docker image.
